version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
     - "2181:2181"
    networks:
      - events-manager

  kafka0:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://${HOST_IP}:9092 
      #For Mac `ipconfig getifaddr en0` For UbuntuServer `ip -o -4 addr show wlan0 | awk '{print $4}' | cut -d/ -f1`
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_CREATE_TOPICS: "user-events:1:1"
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - events-manager
  
  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29093,PLAINTEXT_HOST://${HOST_IP}:9093 
      #For Mac `ipconfig getifaddr en0` For UbuntuServer `ip -o -4 addr show wlan0 | awk '{print $4}' | cut -d/ -f1`
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_CREATE_TOPICS: "user-events:1:1"
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - events-manager

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kafka0
      - kafka1
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "
      echo 'Creating topics...'
      kafka-topics --create --topic orders-confirmed --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 &&
      kafka-topics --create --topic delivery-events --bootstrap-server kafka0:29092 --replication-factor 1 --partitions 1 &&
      echo 'Topics created successfully'
      "
    networks:
      - events-manager

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka0
    ports:
      - "0.0.0.0:8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=base
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka0:29092
      - KAFKA_CLUSTERS_1_NAME=replica
      - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=kafka1:29093
    
    networks:
      - events-manager

networks:
  events-manager:
    external: false
    name: events-manager
    driver: bridge